### ISSUE TITLE
Image Resizer: doesn't work with upper case image extensions

### ISSUE THREAD

**Issue by Inaflean** [searene/Anki-Addons#13]
Image Resizer does not work with upper case image extensions. If I try to use the program on an image called "test.jpg", it works perfectly. If I rename the file to "test.JPG", it no longer works. I believe this issue is why some people have been reporting the extension as not working.

I was able to correct the issue by adding uppercase extension names to the ImageResizer.py at line 200. This is part of "_checkAndResize(mime, editor)_".
`pic = ("jpg","JPG", "jpeg", "JPEG", "png", "PNG", "tif", "TIF", "tiff", "TIFF", "gif", "GIF", "svg", "SVG", "webp", "WEBP")`

Let me know if you need any more info from me. Thanks!

**Comment by searene** [comment]
Hi Inaflean,

Thanks for reporting this issue and providing a solution! I'll fix this and try re-uploading it these days.

Regards,
Searene

**Comment by searene** [comment]
Hi Inaflean,

It's fixed. You can reinstall and check if it works.

commit: c953220cd5cf24e85848c9d01c9857ff296878a2

Regards.
Searene

**Comment by Inaflean** [comment]
Works great. Thanks!
