### ISSUE TITLE
Add Goldendict popup option

### ISSUE THREAD

**Issue by BEST8OY** [searene/Anki-Addons#28]
Hello
Is it possible for you to add Goldendict popup option to your Goldendict addon?
Something like this addon but for Goldendict.
https://ankiweb.net/shared/info/2059332871
I know there is a Hotkey for sending selected words to GD but i want it to be "keyboard-free".

**Comment by searene** [comment]
Hi,

Thanks for the feedback, this addon is used to paste images and audio from GoldenDict, it's not for showing definitions. So I do not prefer to add this functionality. You can check if there is any other dictionary addon that can query words directly in Anki.

**Comment by BEST8OY** [comment]
Unfortunately there is no addon like that.
Thanks for your response.
I wish someone eventually make an addon like this for GD.
