### ISSUE TITLE
Image Resizer Not Working

### ISSUE THREAD

**Issue by daisi145** [searene/Anki-Addons#6]
Hi,

The image resizer does not work for me in Anki 2.0.36. If I use Ctrl + Shift + V to paste, it pastes the same size as if I use Shift + V. I reinstalled it already and still have the same problem. Am I doing something wrong? I even changed it to 200 x 200 just to see if it made it smaller... nope. Nothing seems to work. I should note that I use photos from the clipboard. Thoughts?

**Comment by searene** [comment]
Hi daisi145,

Please try the following steps.
- Menu bar --> Tools --> Add-ons --> Open Add-ons Folder...
- Delete the following files.
  1. a directory called ImageResizer
  2. ImageResizer.py
  3. ImageResizer.pyc
- Install ImageResizer again.

**Comment by daisi145** [comment]
It worked! An amazing add on. Thank you!!
