### ISSUE TITLE
Option for maximum *either* dimension, or select-on-paste

### ISSUE THREAD

**Issue by jamesdeluk** [searene/Anki-Addons#7]
Is it possible to implement a feature where the maximum of either dimension is a certain value?

For example, if I had a 500x1000 image and a 1000x500 image for a single note, one would resize to 200x400, and the other to 400x200. Currently, the options are 400x800 and 400x200, or 200x400 and 800x400. The "either" option would mean the card would be 600x400 or 400x600; otherwise it would be 800x400 or 400x800. This is even more pronounced for cards which are, three or four times as wide as they are tall (or vice versa).

Another option would be to choose the limiting dimension on paste, rather than it being a setting in the menu. Or different keyboard combinations - ctrl shift v for height, ctrl shift opt v for width?

Thanks for your thoughts!

**Comment by searene** [comment]
Hi Jamesdeluk,

I'm not sure if I've got your point. Let's bring up an example. Say, I have a 100x1000 image.

![2017-04-18-230746_155x654_scrot](https://cloud.githubusercontent.com/assets/3351317/25137999/e9cc9d90-248b-11e7-8c8a-c7f98a7e392d.png)

This is my current setting of ImageResizer.

![2017-04-18-225551_927x160_scrot](https://cloud.githubusercontent.com/assets/3351317/25137488/782b2f22-248a-11e7-876e-0807d5864cbd.png)

According to the setting, the image would be scaled to 400x4000.

![2017-04-18-225702_171x639_scrot](https://cloud.githubusercontent.com/assets/3351317/25137522/9549a264-248a-11e7-9f4e-40ba9f98bb5d.png)

This may be way to big, so you would like to tell ImageResize:

> Either the width or the height of the resized image must not be greater than 500.

ImageResizer soon would notice that 4000 is greater than 500, so it would resize the height to 500 and the width to 50 so as to keep the ratio.

![2017-04-18-230342_194x650_scrot](https://cloud.githubusercontent.com/assets/3351317/25137776/524d63a0-248b-11e7-8d87-c244fa91c032.png)

The idea is to make sure the image would not be too large if the height/width ratio is extreme. Is that correct?

**Comment by jamesdeluk** [comment]
Thanks for your quick response!! I've only used ImageResizer to make images _smaller_, not _larger_! So hadn't thought about it this way.

For example, I normally set mine to 300, for both, as I only want a small image (for file size, and for mobile purposes).

Say I had two files (1000x3000 and 3000x1000, although these are all scaled to 25%):
![1000x3000](https://cloud.githubusercontent.com/assets/27723508/25159858/81b7aed6-24ed-11e7-9888-2e41c9f6473d.png) ![3000x1000](https://cloud.githubusercontent.com/assets/27723508/25159857/81b58bce-24ed-11e7-8826-9b76c2ebdf36.png)

Using fixed-width, I would end up with:
![400x133](https://cloud.githubusercontent.com/assets/27723508/25159870/93dcbdcc-24ed-11e7-95bd-bc2c94f2281a.png) ![400x1200](https://cloud.githubusercontent.com/assets/27723508/25159871/93e4fac8-24ed-11e7-94e5-d0e349013eb5.png)

And fixed-height:
![1200x400](https://cloud.githubusercontent.com/assets/27723508/25159878/9f6d5ad4-24ed-11e7-8183-64a9bfd3b0c4.png) ![133x400](https://cloud.githubusercontent.com/assets/27723508/25159879/9f6da91c-24ed-11e7-9040-a312d2baa42a.png)

With the fixed-either, it would be:
![400x133](https://cloud.githubusercontent.com/assets/27723508/25159891/add4f410-24ed-11e7-9974-2bc8519ee016.png) ![133x400](https://cloud.githubusercontent.com/assets/27723508/25159892/addcd8e2-24ed-11e7-92ef-56e11d7c4763.png)
(Obviously 4x as big, due to scaling)

Although, now I do think about it, a on-paste option (or different paste shortcuts) would likely be easier.

**Comment by searene** [comment]
Hi jamesdeluk,

Thanks for your illustration.

Setting another shortcut or option may be easier, but it might be cumbersome for some users, because in this way, a user have to choose the right shortcut before pasting. I think scaling according to the maximum of either dimension might be a better choice.

I've modified Image Resizer to do this kind of job. You can update and see if it works as expected: https://ankiweb.net/shared/info/1214357311

![2017-04-19-234553_1030x153_scrot](https://cloud.githubusercontent.com/assets/3351317/25189000/7b7b9844-255a-11e7-8340-6646e2964241.png)

![2017-04-19-235725_712x531_scrot](https://cloud.githubusercontent.com/assets/3351317/25189527/fc80486c-255b-11e7-8696-fac0e59382d5.png)

Thanks.

**Comment by jamesdeluk** [comment]
Wow, that was so quick. Thank you! I've given it a little trial run and it seems perfect. Thank you again!!
