### ISSUE TITLE
Option to disable upscaling

### ISSUE THREAD

**Issue by glutanimate** [searene/Anki-Addons#8]
First of all: Thanks for your continued support of this add-on. The recent addition of the new scaling option was great!

One thing I have been missing is a setting that disables upscaling. For images that are smaller than the targeted scale I think it makes sense to preserve the original file without any changes. Right now it seems that the add-on always scales images, regardless of their original size.

Thanks for considering this.#

P.S.: I recently featured ImageResizer in [one of my add-on guide videos](https://www.youtube.com/watch?v=FPQxGz61C-o). Hope that's fine!

**Comment by searene** [comment]
Hi @glutanimate,

Glad to see you again. Thanks for this suggestion, I also noticed that most people used ImageResizer for downscaling, so it's totally valid to add an option to disable upscaling.

I have added this option in the code and updated it in AnkiWeb, you may want to check it out.

And a big thanks to your video, it's really great if the addon could be known by more people and make their life/study easier. :)

![2017-06-09-213052_1330x329_scrot](https://user-images.githubusercontent.com/3351317/26978050-951a2692-4d5c-11e7-8761-ca4d99d23c99.png)

**Comment by glutanimate** [comment]
It's working perfectly. Thanks again for the lightning-fast response, @searene!

And no problem, I'm always happy to get the word out about fantastic add-ons like this!
