### ISSUE TITLE
ImageResizer no longer works on Mac

### ISSUE THREAD

**Issue by jvega023** [searene/Anki-Addons#9]
1. It won't let me change the shortcut.
2. When I drag-drop an item, it doesn't actually resize it

**Comment by searene** [comment]
Could you follow these steps?

1. Open Anki, drag and drop an image when adding cards.
2. Open `Tools` --> `Add-ons` --> `Open Add-ons Folder...`
3. Look for a folder called ImageResizer
4. There's a file called `imageResizer.log` in it, paste the contents here so I can see where went wrong.
5. It would be better if you could share you ImageResizer's config via screenshot.

**Comment by jvega023** [comment]
What program do you use to open that .log file? I opened it with Microsoft Word, and it was blank.

Here is my config screen:
<img width="724" alt="screenshot of anki 6-19-17 9-04-28 am" src="https://user-images.githubusercontent.com/16940475/27289105-66466a50-54ce-11e7-9eed-8165fce167e3.png">

When I click "Grab the shortcut" it just stays at this screen, it doesn’t respond to any keyboard combinations:
<img width="724" alt="screenshot of anki 6-19-17 9-04-50 am" src="https://user-images.githubusercontent.com/16940475/27289106-68cbf556-54ce-11e7-85b2-e7d4199f4cd3.png">

**Comment by searene** [comment]
The log file only contains plain text, so you can open it with `TextEdit` on macOS, I think.

Does it work before? If so, you can click on `Reset`, restart Anki and try again.

**Comment by jvega023** [comment]
Yup, it's still blank. And yeah I believe it worked before the last update.

<img width="655" alt="screenshot of textedit 6-19-17 10-03-20 am" src="https://user-images.githubusercontent.com/16940475/27291695-a4819f94-54d6-11e7-8cc8-01a7f1dfec47.png">

**Comment by searene** [comment]
First make sure you open the log file right after you drag and drop an image to Anki.

Does it work if you copy an image from browser and paste it in Anki?

**Comment by jvega023** [comment]
I did open open it right after I drag/dropped an image into Anki, it was blank.

Here is what happens if paste an image into Anki. Same thing happens if I hit the paste shortcut "Shift+Ctrl+V".

<img width="343" alt="screenshot of anki 6-19-17 10-20-35 am" src="https://user-images.githubusercontent.com/16940475/27292507-4560647a-54d9-11e7-93b5-e52ed6de39a5.png">

**Comment by searene** [comment]
I think I just reproduced the problem, and uncheck `Disable upscaling` will make it work again. I will see what went wrong and fix it ASAP. Could you try and see if it also works for you?

**Comment by jvega023** [comment]
Oh yeah it works now, but only if I drag-drop (which is how I use it 99% of the time), the shortcut still gives the same result as my last reply fyi, thanks for your help so far.

**Comment by searene** [comment]
Thank you for reporting the bug, I just updated the addon in AnkiWeb to fix the bug about `Disable upscaling`, you may want to update it and see if it works now with `Disable upscaling` checked. :)

About the shortcut, does it work before?

**Comment by jvega023** [comment]
Yup, it's working with `Disable upscaling` checked.

I hardly ever use the shortcut so I can't say 100% that it worked before, I don’t know to be honest.

**Comment by jvega023** [comment]
Hey sorry to bother you again, but I noticed that while the add-on is working while `Disable upscaling` is checked, it's not actually disabling the upscaling. 

I.e. if I want it to downscale to 400 px, and insert an image that is 200 px, it will upscale it to 400 px.

**Comment by searene** [comment]
Hi jvega023,

Thank you for reaching me again.

This is actually a bug, I fixed it just now and uploaded it to AnkiWeb. Could you try it again and share with me the result? Thanks.

**Comment by jvega023** [comment]
Just tried it, and it's working, thanks again!
